name: "Terraform CI/CD Pipeline"

on:
  push:
    branches:
      - main
      - feature/pipeline
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  security-scan:
    name: "IaC Security & Misconfiguration Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          soft_fail: false # Set to true if you don't want security policy violations to fail the pipeline

      - name: Run Trivy Vulnerability & Misconfig Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          exit-code: '1' # Fails pipeline on HIGH/CRITICAL issues
          severity: 'CRITICAL,HIGH'

  terraform:
    name: "Terraform Init, Plan & Apply"
    needs: security-scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Enviornment/preprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../../

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false